services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://129.121.140.176:8090/api"
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: unless-stopped
