services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://ec2-16-16-207-103.eu-north-1.compute.amazonaws.com/api"
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: unless-stopped
